coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

ignore:
  - "**/*tests.rs"
  - "**/tests/**"

# Configure coverage for specific files
parsers:
  v1:
    # Ignore lines after #[cfg(test)] in all files
    exclude_lines:
      - '#\[cfg\(test\)\]'
      - '#\[test\]'
      - '^\s*mod\s+tests\s*\{'
      - '^\s*//.*'
      - '^\s*/\*.*'

comment:
  layout: "reach, diff, flags, files"
  behavior: default
